services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastcart-php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
      - redis
    ports:
      - "5174:5174"
    networks:
      - fastcart

  mysql:
    image: mysql:8.0
    container_name: fastcart-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fastcart

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fastcart-phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - fastcart

  redis:
    image: redis:alpine
    container_name: fastcart-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - fastcart

  nginx:
    image: nginx:latest
    container_name: fastcart-nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - fastcart

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fastcart-rabbitmq
    ports:
      - "5672:5672"      # RabbitMQ protocol
      - "15672:15672"    # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: fastcart
      RABBITMQ_DEFAULT_PASS: secret
    networks:
      - fastcart

volumes:
  db_data:
  redis_data:

networks:
  fastcart:
