
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fame-php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    ports:
      - "7000:7000"
      - "5174:5174"

  mysql:
    image: mysql:8.0
    container_name: fame_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fame_db
      MYSQL_USER: fame_user
      MYSQL_PASSWORD: fame_pass
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fame-phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8082:80"
    depends_on:
      - mysql
  
  nginx:
    image: nginx:latest
    container_name: fame-nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    
volumes:
  db_data:
